### ISSUE TITLE
ISSUE: Ligas creator should have a country field (optional to avoid international competition issues)

### ISSUE THREAD

**Issue by smeloa** [MeteorBogota/Pollas#34]
Currently ligas does not have a country field this would help when adding teams to a local league as only teams in specific country would be shown.

**Comment by lmatheus** [comment]
done

**Comment by smeloa** [comment]
Not seeing this in the create liga form, or when editing. Also I will modify the JSON so that it includes an INTERNATIONAL country. That it is for something like the World Cup so all country teams get assigned there.

**Comment by smeloa** [comment]
![capture](https://cloud.githubusercontent.com/assets/11669217/13160046/3539ab74-d663-11e5-85b6-e80689b54b60.JPG)

**Comment by lmatheus** [comment]
this was alredy added and optional
